// scripts/classify.mjs
// Builds data/classify.js from the Detective Conan World wiki (English) episode table
// at https://www.detectiveconanworld.com/wiki/Anime.
//
// This is the authoritative canon/filler source ("TV Original" = filler, a manga
// volume reference = canon) and carries the Plot Legend tags shown as icons.
//
// Output keys the data by the JAPANESE episode number (Jpn#) so it joins onto
// data/episodes.js (which uses Japanese numbering). The International number (Int#)
// is stored too, for display alongside.
//
// Usage:  node scripts/classify.mjs   (Node 18+, built-in fetch, no deps)

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const URL = "https://www.detectiveconanworld.com/wiki/Anime";
const UA = "DetectiveConanWatchTracker/1.0 (personal project)";
const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, "..", "data", "classify.js");

// Plot Legend image code -> our tag key
const TAG_MAP = {
  New: "new", Char: "char", Romance: "romance", BO: "bo",
  Past: "past", DB: "db", MK: "mk", FBI: "fbi",
};

const strip = (s) =>
  s.replace(/<[^>]*>/g, "").replace(/&#?\w+;/g, " ").replace(/\s+/g, " ").trim();

async function main() {
  console.log("Fetching DCW anime episode table…");
  const r = await fetch(URL, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error("HTTP " + r.status);
  const html = await r.text();

  const rows = html.split(/<\/tr>/i);
  const out = {};
  let count = 0, filler = 0;

  for (const row of rows) {
    if (!/background:#f2fde9/i.test(row)) continue; // episode rows share this bg colour
    const cells = [...row.matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map((m) => m[1]);
    if (cells.length < 4) continue;

    const jpnRaw = strip(cells[0]);
    if (!/^\d/.test(jpnRaw)) continue;
    const jpn = parseInt(jpnRaw, 10);
    const intNumber = strip(cells[1]);

    // English title lives in the 3rd cell (after Jpn# and Int#)
    const title = strip(cells[2]);

    // manga-source cell: the one mentioning "TV Original", a volume ref (V12), or N/A
    const mangaCell = cells.find((c) => /TV Original|\bV\d+|N\/A/.test(strip(c))) || "";
    const kind = /TV Original/.test(strip(mangaCell)) ? "filler" : "canon";

    const tags = [];
    for (const m of row.matchAll(/Plot-([A-Za-z]+)\.png/g)) {
      const key = TAG_MAP[m[1]];
      if (key && tags.indexOf(key) === -1) tags.push(key);
    }

    out[jpn] = { intNumber, title, kind, tags };
    count++;
    if (kind === "filler") filler++;
  }

  console.log(`Parsed ${count} episodes (canon ${count - filler}, filler ${filler}).`);
  const tagTotals = {};
  Object.values(out).forEach((e) => e.tags.forEach((t) => (tagTotals[t] = (tagTotals[t] || 0) + 1)));
  console.log("Tag totals:", JSON.stringify(tagTotals));

  const banner =
    "// AUTO-GENERATED by scripts/classify.mjs from detectiveconanworld.com/wiki/Anime.\n" +
    "// Keyed by Japanese episode number. Re-run: node scripts/classify.mjs\n";
  await writeFile(OUT, banner + "window.DC_CLASSIFY = " + JSON.stringify(out) + ";\n", "utf8");
  console.log(`Wrote ${OUT}`);
}

main().catch((e) => { console.error("FATAL", e); process.exit(1); });
